### ISSUE TITLE
Does it support redirections?

### ISSUE THREAD

**Issue by davidcopen** [liyao001/BioQueue#1]
Hi,
Does BioQueue support unix input/output redirections like '>', '<' in shell? When I create a step like:
bwa aln {HG19_GENOME} {InputFile} > aln_sa.sai
the output was directed into the job's log file rather than aln_sa.sai.
Copen David

**Comment by liyao001** [comment]
Hi David,
Thank you for your feedback! I have added supports for shell redirections in the latest commit (dd77ac62e7161b13d9bb89cb515063e744e02679), so you can try to run `git pull` to update your local copy of BioQueue.
Li Yao

**Comment by davidcopen** [comment]
Yeah, the problem is solved! Thank you!
